module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  content: [ "./src/**/*.tsx" ],
  safelist: [
    "list-lower-alpha",
    "list-disc",
    "list-circle",
    "list-none",
    "list-decimal",
    "2xs:hidden",
    "xs:hidden",
    "sm:hidden",
    "md:hidden",
    "lg:hidden",
    "xl:hidden",
    "2xl:hidden",
    "2xs:block",
    "xs:block",
    "sm:block",
    "md:block",
    "lg:block",
    "xl:block",
    "2xl:block",
    "2xs:w-60",
    "xs:w-60",
    "sm:w-60",
    "md:w-60",
    "lg:w-60",
    "xl:w-60",
    "2xl:w-60",
    "2xs:mx-2",
    "xs:mx-2",
    "sm:mx-2",
    "md:mx-2",
    "lg:mx-2",
    "xl:mx-2",
    "2xl:mx-2",
    "translate-x-1",
    "translate-x-2",
    "translate-x-3",
    "translate-x-4",
    "translate-x-5",
    "translate-x-6",
    "translate-x-7",
    "translate-x-8",
    "translate-x-9",
    "translate-x-10",
    "translate-x-11",
    "translate-x-12",
    "translate-x-13",
    "translate-x-14",
    "translate-x-15",
    "translate-x-16",
    "translate-x-17",
    "translate-x-18",
    "translate-x-19",
    "translate-x-20",
  ],
  target: "relaxed",
  important: false,
  separator: ":",
  theme: {
    screens: {
      "4xs": "350px",
      "3xs": "400px",
      "2xs": "450px",
      "xs": "550px",
      "sm": "640px",
      "md": "768px",
      "lg": "1024px",
      "xl": "1280px",
    },
    fontFamily: {
      lato: [ "Lato" ]
    },

    extend: {
      maxHeight: {
        almostScreen: "80vh"
      },
      height: {
        22: "5.5rem",
        100: "25rem",
        104: "26rem",
        108: "27rem",
        112: "28rem",
        120: "30rem",
        180: "45rem",
        200: "50rem",
        240: "60rem",
        almostScreen: "80vw"
      },
      maxWidth: {
        16: "4rem",
        32: "8rem",
        60: "15rem",
        80: "20rem",
        100: "25rem",
        112: "28rem",
        120: "30rem",
        180: "45rem",
        200: "50rem",
        240: "60rem",
        almostScreen: "80vw"
      },
      minWidth: {
        60: "15rem",
        68: "17rem",
        80: "20rem",
        100: "25rem",
        120: "30rem",
        180: "45rem",
        200: "50rem",
        240: "60rem",
        almostScreen: "80vw"
      },
      width: {
        26: "6.7rem",
        100: "25rem",
        120: "30rem",
        180: "45rem",
        200: "50rem",
        240: "60rem",
        almostScreen: "80vw"
      },
      colors: {
        primary: "#239FA7",
        divider: "#EFEFF8",
        dpTextBlack: "#222222",
        dpTextGray: "#848999",
        dpGrayLight: "#EFEFEF",
        dpBlue: "#239FA7",
        dpYellowLight: "#FFE9D0",
        dpPinkLight: "#FCE5E6",
        dpRed: "#EE5D60",
        dpGreen: "#0d944a",
        dpOrangeMedium: "#e28733",
        dpAlphaGreen: "#45ad74",
        dpLightGreen: "#e1f6ec",
        dpOrange: "#f5a623",
        dpOrangeLight: "#ffe140",
        dpOrangeDark: "#D57300",
        dpOrangeVeryDark:"#B55300",
        dpMud: "#D06F00",
        dpGreenDark: "#165c50",

        dpLightGray: "#DCDCDC",
        dpGray: "#848999",
        dpGrayDark: "#292E42",

        transparent: "transparent",
        current: "currentColor",

        black: "#000",
        white: "#fff",
        almostWhite: "#F6F6F6",

        borderDefault: "#e5e7eb"
      },
      backgroundSize: {
        auto: "auto",
        cover: "cover",
        contain: "contain",
        300: "300%",
        500: "500%",
      },
      borderColor: theme => ({
        ...theme("colors"),
        default: theme("colors.gray.300", "currentColor"),
      }),
      borderOpacity: theme => theme("opacity"),
      borderRadius: {
        none: "0",
        sm: "0.125rem",
        default: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        half: "50%"
      },
      borderWidth: {
        default: "1px",
        0: "0",
        1: "1px",
        2: "2px",
        4: "4px",
        8: "8px",
      },
      boxShadow: {
        "xs": "0 0 0 1px rgba(0, 0, 0, 0.05)",
        "sm": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        "default":
          "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
        "md":
          "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        "sym-md":
          "0 0 5px 2px rgba(0, 0, 0, 0.1)",
        "lg":
          "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        "sym-lg":
          "0 0 8px 3px rgba(0, 0, 0, 0.1)",
        "xl":
          "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        "inner": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
        "inner-lg": "inset 0 4px 4px rgba(0, 0, 0, 0.06)",
        "outline": "0 0 0 3px rgba(66, 153, 225, 0.5)",
        "none": "none",
        "primary": "0px 3px 20px rgba(85, 95, 109, 0.08)",
      },
      container: {},
      cursor: {
        "auto": "auto",
        "default": "default",
        "pointer": "pointer",
        "wait": "wait",
        "text": "text",
        "move": "move",
        "not-allowed": "not-allowed",
      },
      divideColor: theme => theme("borderColor"),
      divideOpacity: theme => theme("borderOpacity"),
      divideWidth: theme => theme("borderWidth"),
      fill: {
        current: "currentColor",
      },
      flex: {
        1: "1 1 0%",
        auto: "1 1 auto",
        initial: "0 1 auto",
        none: "none",
      },
      flexGrow: {
        0: "0",
        1: "1",
        default: "1",
      },
      flexShrink: {
        0: "0",
        1: "1",
        default: "1",
      },
      listStyleType: {
        "circle": "circle",
        "lower-alpha": "lower-alpha"
      },
      scale: {
        200: "200%",
        250: "250%",
        300: "300%"
      },
      right: {
        "4/5": "80%",
        "-4/5": "-80%",
      }
    },
  },
  variants: {
    accessibility: [ "responsive", "focus" ],
    alignContent: [ "responsive" ],
    alignItems: [ "responsive" ],
    alignSelf: [ "responsive" ],
    appearance: [ "responsive" ],
    backgroundAttachment: [ "responsive" ],
    backgroundClip: [ "responsive" ],
    backgroundColor: [ "responsive", "hover", "focus" ],
    backgroundImage: [ "responsive" ],
    gradientColorStops: [ "responsive", "hover", "focus" ],
    backgroundOpacity: [ "responsive", "hover", "focus" ],
    backgroundPosition: [ "responsive" ],
    backgroundRepeat: [ "responsive" ],
    backgroundSize: [ "responsive" ],
    borderCollapse: [ "responsive" ],
    borderColor: [ "responsive", "hover", "focus" ],
    borderOpacity: [ "responsive", "hover", "focus" ],
    borderRadius: [ "responsive" ],
    borderStyle: [ "responsive" ],
    borderWidth: [ "responsive" ],
    boxShadow: [ "responsive", "hover", "focus" ],
    boxSizing: [ "responsive" ],
    container: [ "responsive" ],
    cursor: [ "responsive" ],
    display: [ "responsive" ],
    divideColor: [ "responsive" ],
    divideOpacity: [ "responsive" ],
    divideStyle: [ "responsive" ],
    divideWidth: [ "responsive" ],
    fill: [ "responsive" ],
    flex: [ "responsive" ],
    flexDirection: [ "responsive" ],
    flexGrow: [ "responsive" ],
    flexShrink: [ "responsive" ],
    flexWrap: [ "responsive" ],
    float: [ "responsive" ],
    clear: [ "responsive" ],
    fontFamily: [ "responsive" ],
    fontSize: [ "responsive" ],
    fontSmoothing: [ "responsive" ],
    fontVariantNumeric: [ "responsive" ],
    fontStyle: [ "responsive" ],
    fontWeight: [ "responsive", "hover", "focus" ],
    height: [ "responsive" ],
    inset: [ "responsive" ],
    justifyContent: [ "responsive" ],
    justifyItems: [ "responsive" ],
    justifySelf: [ "responsive" ],
    letterSpacing: [ "responsive" ],
    lineHeight: [ "responsive" ],
    listStylePosition: [ "responsive" ],
    listStyleType: [ "responsive" ],
    margin: [ "responsive" ],
    maxHeight: [ "responsive" ],
    maxWidth: [ "responsive" ],
    minHeight: [ "responsive" ],
    minWidth: [ "responsive" ],
    objectFit: [ "responsive" ],
    objectPosition: [ "responsive" ],
    opacity: [ "responsive", "hover", "focus" ],
    order: [ "responsive" ],
    outline: [ "responsive", "focus" ],
    overflow: [ "responsive" ],
    overscrollBehavior: [ "responsive" ],
    padding: [ "responsive" ],
    placeContent: [ "responsive" ],
    placeItems: [ "responsive" ],
    placeSelf: [ "responsive" ],
    placeholderColor: [ "responsive", "focus" ],
    placeholderOpacity: [ "responsive", "focus" ],
    pointerEvents: [ "responsive" ],
    position: [ "responsive" ],
    resize: [ "responsive" ],
    space: [ "responsive" ],
    stroke: [ "responsive" ],
    strokeWidth: [ "responsive" ],
    tableLayout: [ "responsive" ],
    textAlign: [ "responsive" ],
    textColor: [ "responsive", "hover", "focus" ],
    textOpacity: [ "responsive", "hover", "focus" ],
    textDecoration: [ "responsive", "hover", "focus" ],
    textTransform: [ "responsive" ],
    userSelect: [ "responsive" ],
    verticalAlign: [ "responsive" ],
    visibility: [ "responsive" ],
    whitespace: [ "responsive" ],
    width: [ "responsive" ],
    wordBreak: [ "responsive" ],
    zIndex: [ "responsive" ],
    gap: [ "responsive" ],
    gridAutoFlow: [ "responsive" ],
    gridTemplateColumns: [ "responsive" ],
    gridColumn: [ "responsive" ],
    gridColumnStart: [ "responsive" ],
    gridColumnEnd: [ "responsive" ],
    gridTemplateRows: [ "responsive" ],
    gridRow: [ "responsive" ],
    gridRowStart: [ "responsive" ],
    gridRowEnd: [ "responsive" ],
    transform: [ "responsive" ],
    transformOrigin: [ "responsive" ],
    scale: [ "responsive", "hover", "focus" ],
    rotate: [ "responsive", "hover", "focus" ],
    translate: [ "responsive", "hover", "focus" ],
    skew: [ "responsive", "hover", "focus" ],
    transitionProperty: [ "responsive" ],
    transitionTimingFunction: [ "responsive" ],
    transitionDuration: [ "responsive" ],
    transitionDelay: [ "responsive" ],
    animation: [ "responsive" ],
  },
  corePlugins: {},
  plugins: [],
};
